//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proVue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        public int ID_Auto { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Año_Fabricacion { get; set; }
        public string Tipo { get; set; }
        public int CantPasajeros { get; set; }
        public string TipoTrans { get; set; }
        public decimal Precio { get; set; }
        public string Tipo_Moneda { get; set; }
    }
}
